// Copies contract ABIs from Foundry's build output into src/app/abi.ts (typed `as const` for viem).
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
// `--check`: exit 1 if src/app/abi.ts is stale against contracts/out. The build runs this so a contract change
// can never ship with the old ABI (a stale struct layout decodes into the wrong fields).
const check = process.argv.includes('--check');

const out = new URL('../../contracts/out/', import.meta.url);
const abi = (file, name) => JSON.parse(readFileSync(new URL(`${file}/${name}.json`, out))).abi;

const artAbi = [
  { type: 'function', name: 'svg', stateMutability: 'pure', inputs: [{ name: 'seed', type: 'bytes21' }, { name: 'paidAt', type: 'uint64' }], outputs: [{ type: 'string' }] },
];

const entries = {
  batchAbi: abi('Batch.sol', 'Batch'),
  factoryAbi: abi('BatchFactory.sol', 'BatchFactory'),
  sweeperAbi: abi('Sweeper.sol', 'Sweeper'),
  creditsAbi: abi('ICredits.sol', 'ICredits'),
  creditArtAbi: [...abi('ICredits.sol', 'ICreditArt'), ...artAbi],
  unionFormatsAbi: abi('UnionFormats.sol', 'UnionFormats'),
  tokenAdapterAbi: abi('TokenAdapter.sol', 'TokenAdapter'),
};

let ts = '// Generated by scripts/abi.mjs from contracts/out. Do not edit.\n\n';
for (const [k, v] of Object.entries(entries)) ts += `export const ${k} = ${JSON.stringify(v, null, 2)} as const;\n\n`;
const target = new URL('../src/app/abi.ts', import.meta.url);
if (check) {
  if ((existsSync(target) ? readFileSync(target, 'utf8') : '') !== ts) {
    console.error('src/app/abi.ts is stale: `forge build` in contracts, then `pnpm abi`.');
    process.exit(1);
  }
  console.log('abi.ts is current');
} else {
  writeFileSync(target, ts);
  console.log('wrote src/app/abi.ts');
}
