// Copies contract ABIs from Foundry's build output into src/app/abi.ts (typed `as const` for viem).
import { readFileSync, writeFileSync } from 'node:fs';

const out = new URL('../../contracts/out/', import.meta.url);
const abi = (file, name) => JSON.parse(readFileSync(new URL(`${file}/${name}.json`, out))).abi;

const artAbi = [
  { type: 'function', name: 'svg', stateMutability: 'pure', inputs: [{ name: 'seed', type: 'bytes21' }, { name: 'paidAt', type: 'uint64' }], outputs: [{ type: 'string' }] },
];

const entries = {
  batchAbi: abi('Batch.sol', 'Batch'),
  factoryAbi: abi('BatchFactory.sol', 'BatchFactory'),
  sweeperAbi: abi('Sweeper.sol', 'Sweeper'),
  creditsAbi: abi('ICredits.sol', 'ICredits'),
  creditArtAbi: [...abi('ICredits.sol', 'ICreditArt'), ...artAbi],
};

let ts = '// Generated by scripts/abi.mjs from contracts/out. Do not edit.\n\n';
for (const [k, v] of Object.entries(entries)) ts += `export const ${k} = ${JSON.stringify(v, null, 2)} as const;\n\n`;
writeFileSync(new URL('../src/app/abi.ts', import.meta.url), ts);
console.log('wrote src/app/abi.ts');
