// Generated by scripts/abi.mjs from contracts/out. Do not edit.

export const batchAbi = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "AUCTION_LENGTH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "BURN_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EXTENSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "LOCK_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_ALLOWLIST",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_CREATOR_FEE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_NAME",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_PROTOCOL_FEE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_RAISE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_RAISE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "REFUND_GAS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "RESERVE_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SIZE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "allowed",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "allowlistSize",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "arrangement",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum Batch.Arrangement"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "art",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICreditArt"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assemble",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assembledAt",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "auctionEnd",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bid",
    "inputs": [],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "burnDeadline",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "burnOrder",
    "inputs": [],
    "outputs": [
      {
        "name": "out",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "canTake",
    "inputs": [
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [
      {
        "name": "ok",
        "type": "bool[]",
        "internalType": "bool[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claim",
    "inputs": [
      {
        "name": "depositor",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "claimStatement",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "claimable",
    "inputs": [
      {
        "name": "depositor",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimed",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "count",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "creator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "creatorFeeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "credits",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICredits"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deadline",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "depositFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "depositorOf",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "factory",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IBatchFactory"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "filledAt",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "filter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Batch.Filter",
        "components": [
          {
            "name": "palettes",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "prints",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "weights",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "eights",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "paidFrom",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "paidTo",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "idFrom",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "idTo",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "layout0",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "layout1",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "bitsFrom",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "bitsTo",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "layoutTrait",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "highBid",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "highBidder",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ids",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "creator_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "name_",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "filter_",
        "type": "tuple",
        "internalType": "struct Batch.Filter",
        "components": [
          {
            "name": "palettes",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "prints",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "weights",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "eights",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "paidFrom",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "paidTo",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "idFrom",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "idTo",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "layout0",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "layout1",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "bitsFrom",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "bitsTo",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "layoutTrait",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      },
      {
        "name": "allowlist_",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "reserve_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "protocolFeeBps_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "creatorFeeBps_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "arrangement_",
        "type": "uint8",
        "internalType": "enum Batch.Arrangement"
      },
      {
        "name": "split_",
        "type": "uint8",
        "internalType": "enum Batch.Split"
      },
      {
        "name": "deadline_",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "keyOf",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "layout",
    "inputs": [],
    "outputs": [
      {
        "name": "out",
        "type": "uint8[80]",
        "internalType": "uint8[80]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "layoutOrder",
    "inputs": [],
    "outputs": [
      {
        "name": "out",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lockAt",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minBid",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "name",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "onERC721Received",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "owed",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "passes",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "payoutPerShare",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "payoutPerUnit",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "phase",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum Batch.Phase"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "protocolFeeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rescue",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "reserve",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "restartCountdown",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settle",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settled",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sharesOf",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "slots",
    "inputs": [],
    "outputs": [
      {
        "name": "ids_",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "depositors",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "split",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum Batch.Split"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "state",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum Batch.State"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "statement",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "statementId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "statementUnclaimed",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "summary",
    "inputs": [],
    "outputs": [
      {
        "name": "s",
        "type": "tuple",
        "internalType": "struct Batch.Summary",
        "components": [
          {
            "name": "state",
            "type": "uint8",
            "internalType": "enum Batch.State"
          },
          {
            "name": "arrangement",
            "type": "uint8",
            "internalType": "enum Batch.Arrangement"
          },
          {
            "name": "canAssemble",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "phase",
            "type": "uint8",
            "internalType": "enum Batch.Phase"
          },
          {
            "name": "lockAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "creator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "count",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "filledAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "assembledAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "auctionEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "reserve",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minBid",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "creatorFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "protocolFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "filter",
            "type": "tuple",
            "internalType": "struct Batch.Filter",
            "components": [
              {
                "name": "palettes",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "prints",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "weights",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "eights",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "paidFrom",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "paidTo",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "idFrom",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "idTo",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minScore",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxScore",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "layout0",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "layout1",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "bitsFrom",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "bitsTo",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "layoutTrait",
                "type": "uint8",
                "internalType": "uint8"
              }
            ]
          },
          {
            "name": "allowlistSize",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "statement",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "statementId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "highBidder",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "highBid",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "payoutPerShare",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "split",
            "type": "uint8",
            "internalType": "enum Batch.Split"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unitsOf",
    "inputs": [
      {
        "name": "depositor",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "units",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "withdrawOwed",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Assembled",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "statement",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "statementId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "order",
        "type": "uint256[]",
        "indexed": false,
        "internalType": "uint256[]"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Bid",
    "inputs": [
      {
        "name": "bidder",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "auctionEnd",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Claimed",
    "inputs": [
      {
        "name": "depositor",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Deposited",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "count",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Filled",
    "inputs": [
      {
        "name": "lockAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Owed",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Rescued",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Settled",
    "inputs": [
      {
        "name": "winner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "protocolFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "creatorFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "payoutPerShare",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StatementUnclaimed",
    "inputs": [
      {
        "name": "winner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "count",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AllowlistTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyDeposited",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "AlreadyInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ArrangementRetired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AuctionOver",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AuctionRunning",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadFilter",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadOrder",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BidTooLow",
    "inputs": [
      {
        "name": "min",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CreatorFeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CreditsNotBurned",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Excluded",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LayoutMismatch",
    "inputs": [
      {
        "name": "slot",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NameTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoDepositor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoSlot",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotDepositor",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotFactory",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotHeld",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotStray",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotWinner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingToClaim",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PaymentFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProtocolFeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveTooLow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StatementNotReceived",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongPhase",
    "inputs": [
      {
        "name": "phase",
        "type": "uint8",
        "internalType": "enum Batch.Phase"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongState",
    "inputs": [
      {
        "name": "state",
        "type": "uint8",
        "internalType": "enum Batch.State"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongToken",
    "inputs": []
  }
] as const;

export const factoryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "credits_",
        "type": "address",
        "internalType": "contract ICredits"
      },
      {
        "name": "ratings_",
        "type": "address",
        "internalType": "contract IRatings"
      },
      {
        "name": "assembler_",
        "type": "address",
        "internalType": "contract IAssembler"
      },
      {
        "name": "setter_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feeRecipient_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "protocolFeeBps_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "creatorFeeBps_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minOpen_",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ASSEMBLER_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_CREATOR_FEE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_DURATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_PROTOCOL_FEE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_DURATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "activateAssembler",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assembler",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAssembler"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assemblerActiveAt",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assemblerSetter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "batchCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "batches",
    "inputs": [
      {
        "name": "offset",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "create",
    "inputs": [
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "filter",
        "type": "tuple",
        "internalType": "struct Batch.Filter",
        "components": [
          {
            "name": "palettes",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "prints",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "weights",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "eights",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "paidFrom",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "paidTo",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "idFrom",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "idTo",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "layout0",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "layout1",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "bitsFrom",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "bitsTo",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "layoutTrait",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      },
      {
        "name": "allowlist",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "reserve",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "arrangement",
        "type": "uint8",
        "internalType": "enum Batch.Arrangement"
      },
      {
        "name": "split",
        "type": "uint8",
        "internalType": "enum Batch.Split"
      },
      {
        "name": "duration",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "expectProtocolFeeBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "expectCreatorFeeBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "batch",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "creatorFeeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "credits",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICredits"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deposit",
    "inputs": [
      {
        "name": "batch",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "depositFor",
    "inputs": [
      {
        "name": "batch",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "feeRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "implementation",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isBatch",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minOpen",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingAssembler",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAssembler"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingUntil",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proposeAssembler",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "contract IAssembler"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "protocolFeeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ratings",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRatings"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setFees",
    "inputs": [
      {
        "name": "protocolFeeBps_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "creatorFeeBps_",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AssemblerActivated",
    "inputs": [
      {
        "name": "assembler",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssemblerProposed",
    "inputs": [
      {
        "name": "assembler",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "activatableAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BatchCreated",
    "inputs": [
      {
        "name": "batch",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "creator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "index",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeesSet",
    "inputs": [
      {
        "name": "protocolFeeBps",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "creatorFeeBps",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AssemblerFixed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadDuration",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CreatorFeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FailedDeployment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeesChanged",
    "inputs": [
      {
        "name": "protocolFeeBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "creatorFeeBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InsufficientBalance",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoAssembler",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoDepositor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoFeeRecipient",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotFeeRecipient",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSetter",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingPending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProtocolFeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooFewToOpen",
    "inputs": [
      {
        "name": "min",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;

export const sweeperAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "seaport_",
        "type": "address",
        "internalType": "contract ISeaport"
      },
      {
        "name": "factory_",
        "type": "address",
        "internalType": "contract BatchFactory"
      },
      {
        "name": "feeBps_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "fwa_",
        "type": "address",
        "internalType": "contract IFWAMarket"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "MAX_FEE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "credits",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICredits"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "factory",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract BatchFactory"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "fwa",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IFWAMarket"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quote",
    "inputs": [
      {
        "name": "listingsTotal",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "seaport",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISeaport"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setFee",
    "inputs": [
      {
        "name": "feeBps_",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sweep",
    "inputs": [
      {
        "name": "batch",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "orders",
        "type": "tuple[]",
        "internalType": "struct AdvancedOrder[]",
        "components": [
          {
            "name": "parameters",
            "type": "tuple",
            "internalType": "struct OrderParameters",
            "components": [
              {
                "name": "offerer",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "zone",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "offer",
                "type": "tuple[]",
                "internalType": "struct OfferItem[]",
                "components": [
                  {
                    "name": "itemType",
                    "type": "uint8",
                    "internalType": "enum ItemType"
                  },
                  {
                    "name": "token",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "identifierOrCriteria",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "startAmount",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "endAmount",
                    "type": "uint256",
                    "internalType": "uint256"
                  }
                ]
              },
              {
                "name": "consideration",
                "type": "tuple[]",
                "internalType": "struct ConsiderationItem[]",
                "components": [
                  {
                    "name": "itemType",
                    "type": "uint8",
                    "internalType": "enum ItemType"
                  },
                  {
                    "name": "token",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "identifierOrCriteria",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "startAmount",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "endAmount",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "recipient",
                    "type": "address",
                    "internalType": "address payable"
                  }
                ]
              },
              {
                "name": "orderType",
                "type": "uint8",
                "internalType": "enum OrderType"
              },
              {
                "name": "startTime",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "endTime",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "zoneHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "salt",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "conduitKey",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "totalOriginalConsiderationItems",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "numerator",
            "type": "uint120",
            "internalType": "uint120"
          },
          {
            "name": "denominator",
            "type": "uint120",
            "internalType": "uint120"
          },
          {
            "name": "signature",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "extraData",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "minBought",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxFeeBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "sweepWithFWA",
    "inputs": [
      {
        "name": "batch",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "orders",
        "type": "tuple[]",
        "internalType": "struct AdvancedOrder[]",
        "components": [
          {
            "name": "parameters",
            "type": "tuple",
            "internalType": "struct OrderParameters",
            "components": [
              {
                "name": "offerer",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "zone",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "offer",
                "type": "tuple[]",
                "internalType": "struct OfferItem[]",
                "components": [
                  {
                    "name": "itemType",
                    "type": "uint8",
                    "internalType": "enum ItemType"
                  },
                  {
                    "name": "token",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "identifierOrCriteria",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "startAmount",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "endAmount",
                    "type": "uint256",
                    "internalType": "uint256"
                  }
                ]
              },
              {
                "name": "consideration",
                "type": "tuple[]",
                "internalType": "struct ConsiderationItem[]",
                "components": [
                  {
                    "name": "itemType",
                    "type": "uint8",
                    "internalType": "enum ItemType"
                  },
                  {
                    "name": "token",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "identifierOrCriteria",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "startAmount",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "endAmount",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "recipient",
                    "type": "address",
                    "internalType": "address payable"
                  }
                ]
              },
              {
                "name": "orderType",
                "type": "uint8",
                "internalType": "enum OrderType"
              },
              {
                "name": "startTime",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "endTime",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "zoneHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "salt",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "conduitKey",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "totalOriginalConsiderationItems",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "numerator",
            "type": "uint120",
            "internalType": "uint120"
          },
          {
            "name": "denominator",
            "type": "uint120",
            "internalType": "uint120"
          },
          {
            "name": "signature",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "extraData",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "fwaListings",
        "type": "tuple[]",
        "internalType": "struct Sweeper.FWAListing[]",
        "components": [
          {
            "name": "listingId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "minBought",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxFeeBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "event",
    "name": "FeeSet",
    "inputs": [
      {
        "name": "feeBps",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Swept",
    "inputs": [
      {
        "name": "buyer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "batch",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "bought",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "spent",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "fee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "FeeChanged",
    "inputs": [
      {
        "name": "feeBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "FeeNotCovered",
    "inputs": [
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "FeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoFWA",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotACredit",
    "inputs": [
      {
        "name": "orderIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotAFWACredit",
    "inputs": [
      {
        "name": "fwaIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotBatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotDelivered",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotFeeRecipient",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PaymentFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooFewBought",
    "inputs": [
      {
        "name": "bought",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "Underpaid",
    "inputs": []
  }
] as const;

export const creditsAbi = [
  {
    "type": "function",
    "name": "approve",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "art",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICreditArt"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "balanceOf",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "burn",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes21[]",
        "internalType": "bytes21[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getApproved",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isApprovedForAll",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSealed",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ownerOf",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "safeTransferFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "safeTransferFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "seedOf",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes21",
        "internalType": "bytes21"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setApprovalForAll",
    "inputs": [
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "approved",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "timestampOf",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "tokensOf",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Approval",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "approved",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ApprovalForAll",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "approved",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Transfer",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  }
] as const;

export const creditArtAbi = [
  {
    "type": "function",
    "name": "describe",
    "inputs": [
      {
        "name": "seed",
        "type": "bytes21",
        "internalType": "bytes21"
      },
      {
        "name": "paidAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ICreditArt.Read",
        "components": [
          {
            "name": "hash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "marks",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "capacity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "plates",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "colors",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "eights",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tier",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "weight",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "register",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "eightsLabel",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "svg",
    "stateMutability": "pure",
    "inputs": [
      {
        "name": "seed",
        "type": "bytes21"
      },
      {
        "name": "paidAt",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "type": "string"
      }
    ]
  }
] as const;

